num_trials: 5
num_workers: 8 # for dataloaders

model:
  M: 10 # number of predictors, if stumps: 2*M per dimension
  prior: 1 # param of the Dirichlet prior
  pred: "rf" # random forest or "stumps-uniform"
  bootstrap: 0.5 # for informed priors
  tree_depth: None # for informed priors
  m_prior: 0.5 # for informed priors: use first m * N_train points to learn the prior, and last (1-m) * N_train to learn the posterior

training:
  seed: 23042021
  lr: 0.1
  batch_size: 100
  num_epochs: 100
  risk: "margin" # or f2, SO, FO, Bin
  rand_n: 100 # only for Bin
  gamma: 0 # only for margin

dataset: 'TTT'

bound:
  delta: 0.05
